### PR TITLE
Complete Assignment

### PR DESCRIPTION
**Pull request by Ravikisha**
## Submitting for the housewareHQ

i complete the task given in readme file and try my best to fill the requirements.

### CODE REVIEW

**Comment by shubh24** [comment]
@Ravikisha Please follow the instructions in Github Classroom and create a new repository for your submission. Your assignment will be assessed on that repo.

**Comment by Ravikisha** [comment]
I am not able to get into the GitHub classroom. There is a message `Maximum application limit reached! You cannot apply to this octernship at this moment.` on the home page of octernship. is there any chance I can participate?

**Comment by Fikunmi01** [comment]
How do we know when we're being reviewed

**Comment by theBstar** [comment]
Hey @Ravikisha , Thanks for the Submission.

We have a high number of submissions and with that, the bar is set real high. Unfortunately, you didn't make it to the top few candidates we are interviewing.

Wishing you all the best.

Thanks again,
Bikram.

**Pull request closed without merging**
